### ISSUE TITLE
Is it possible for the `on_click` lambda function to fire even when the notification has timed out

### ISSUE THREAD

**Issue by ZhangTianrong** [GitHub30/win11toast#20]
I am trying to create a REST api, such that a request can trigger a toast and clicking the toast copies the content of the request to the clipboard. Something like:
```python
from win11toast import toast_async
from flask import Flask, request

app = Flask(__name__)

@app.route("/toast", methods=['POST'])
async def get_data():
    content = request.form["content"]
    await toast_async(content, "click to copy", on_click=lambda _:pyclip.copy(content))
    return 'OK'
```
It works fine when the notification first show up but doesn't work when it times out and gets stored in the notification center. Is it possible not to mark the `dismissed_future` as done when the dismissed reason is `TIMED_OUT`? 

I am not familiar enough with `asyncio`, so I just made the following modifications to line 355 in `win11toast.py`:
```python
dismissed_token = notification.add_dismissed(
    lambda _, event_args: None if ToastDismissedEventArgs._from(event_args).reason == 2 else loop.call_soon_threadsafe(
    dismissed_future.set_result, on_dismissed(result_wrapper(ToastDismissedEventArgs._from(event_args).reason)))
)
```
It seems to be working, but I am not sure.

**Comment by GitHub30** [comment]
Thank you for your comment. You can solve it by generating a python file.

https://user-images.githubusercontent.com/12811398/224033287-8eae0221-a33e-4475-96ae-52bdaf9ac7cf.mp4

```python
import tempfile
from flask import Flask, request
from win11toast import notify

app = Flask(__name__)


@app.route('/toast', methods=['POST'])
def hello_world():
    content = request.form['content']
    fp = tempfile.NamedTemporaryFile(suffix='.pyw', delete=False)
    fp.write(f'import pyclip;pyclip.copy("{content}")'.encode())
    notify(content, 'click to copy', on_click=fp.name)
    return 'OK'
```

**Comment by jaydeepjondhale** [comment]
@GitHub30, i was facing the same issue and tried this solution but not worked for me, can you please help me
i have tried the above same code .

**Comment by jaydeepjondhale** [comment]
@GitHub30  is there any way to do this same without using tempfile?
