### ISSUE TITLE
你好，请问怎么自定义弹窗上面的程序名称

### ISSUE THREAD

**Issue by Uiisland** [GitHub30/win11toast#22]

**Comment by Nicolasking007** [comment]
[可以参考我的项目](https://github.com/Nicolasking007/Wintoast)

**Comment by happycola233** [comment]
您好，根据：https://learn.microsoft.com/zh-cn/windows/apps/design/shell/tiles-and-notifications/send-local-toast-other-apps

您可以在注册表：`计算机\HKEY_LOCAL_MACHINE\SOFTWARE\Classes\AppUserModelId` 下新建项（项的名称自定，作为**app_id**），在项中指定图标和程序名称（可参考`AppUserModelId`下的其它项）

然后在Python代码toast方式中，添加**app_id**参数，例如：`toast(title, text, app_id='注册表中新建项的名称')`

**Comment by Uiisland** [comment]
好的，非常感谢您的回复

发自我的iPhone

**Comment by Uiisland** [comment]
好的，非常感谢您的回复

发自我的iPhone
