### ISSUE TITLE
Hopes that some parameters can be customized without being written

### ISSUE THREAD

**Issue by Nicolasking007** [GitHub30/win11toast#6]
- Hope app_id ... can be customized without having to write it. Although I modified it myself
-  A very useful project Thank you very much ！

**Comment by GitHub30** [comment]
Thank you for your comment. It can be customized with the app_id argument.

```powershell
pip install -U win11toast
```

```python
from win11toast import toast

toast('Hello Python🐍', app_id='Microsoft.WindowsTerminal_8wekyb3d8bbwe!App')
```

![image](https://user-images.githubusercontent.com/12811398/195972754-b53c3739-b83f-4692-9283-9092c0e3b278.png)

changes https://github.com/GitHub30/win11toast/commit/82135f4ff6c613789216e4c26c51adb1c7789d95

List app ids

```powershell
Get-StartApps
```

![image](https://user-images.githubusercontent.com/12811398/195972902-ab81d650-c4be-4710-967f-f27dc4408a20.png)
