### ISSUE TITLE
Toast for buttons

### ISSUE THREAD

**Issue by Insomnia00** [GitHub30/win11toast#9]
For toast buttons apparently there's no way to know which button was clicked, I can input arguments and derived from there or is there other way?

**Comment by GitHub30** [comment]
You can handle the input with `on_click`.

```python
from win11toast import toast

toast('gain value', 'please chose', buttons=['A', 'B', 'C'], on_click=lambda args: print('clicked!', args))
# clicked! {'arguments': 'http:B', 'user_input': {}} on B clicked
```

https://github.com/GitHub30/win11toast/discussions/3

**Comment by Insomnia00** [comment]
yeap i have a similar solution (just wondering if theres any other func), this can also added to your readme.md , its a pretty good function
